#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Meshing
runApplication blockMesh
runApplication surfaceFeatures
runApplication decomposePar
runParallel snappyHexMesh -overwrite
runApplication reconstructParMesh -constant 
rm -rf processor*
rm -rf log.decomposePar

# Create the inlet/outlet and AMI patches
runApplication createBaffles -overwrite
runApplication mergeOrSplitBaffles -split -overwrite

# Renumbering
runApplication renumberMesh -noFields -overwrite
runApplication checkMesh

#------------------------------------------------------------------------------
